"""change_batches + change_batch_items (docs/DATABASE.md §8-9)."""

from __future__ import annotations

from datetime import datetime
from typing import Final

from sqlalchemy import (
    CheckConstraint,
    ForeignKeyConstraint,
    Index,
    String,
    Text,
    text,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import SERVER_NOW, Base, UTCTimestamp, UUIDKeyMixin

CHANGE_ACTIONS: Final = ("CREATE", "DELETE", "UPSERT")
CHANGE_STATUSES: Final = ("PENDING", "INSYNC")
INSYNC_AFTER_SECONDS: Final = 60


class ChangeBatch(UUIDKeyMixin, Base):
    """The change id is `C` + 13 uppercase alphanumerics (docs/DATABASE.md §1),
    generated by the service inside the creating transaction."""

    __tablename__ = "change_batches"
    __table_args__ = (
        CheckConstraint("id GLOB 'C[A-Z0-9]*'", name="ck_change_batches_id_format"),
        CheckConstraint("status IN ('PENDING','INSYNC')", name="ck_change_batches_status_values"),
        ForeignKeyConstraint(
            ["hosted_zone_id"],
            ["hosted_zones.id"],
            ondelete="CASCADE",
            name="fk_change_batches_hosted_zone_id_hosted_zones",
        ),
        Index("ix_batches_zone_time", "hosted_zone_id", "submitted_at"),
    )

    id: Mapped[str] = mapped_column(String(32), primary_key=True)
    hosted_zone_id: Mapped[str] = mapped_column(String(32))
    status: Mapped[str] = mapped_column(
        String(16), server_default=text("'PENDING'"), default="PENDING"
    )
    submitted_at: Mapped[datetime] = mapped_column(UTCTimestamp, server_default=SERVER_NOW)
    comment: Mapped[str | None] = mapped_column(Text)


class ChangeBatchItem(UUIDKeyMixin, Base):
    __tablename__ = "change_batch_items"
    __table_args__ = (
        CheckConstraint(
            "action IN ('CREATE','DELETE','UPSERT')", name="ck_change_batch_items_action_values"
        ),
        ForeignKeyConstraint(
            ["change_batch_id"],
            ["change_batches.id"],
            ondelete="CASCADE",
            name="fk_change_batch_items_change_batch_id_change_batches",
        ),
    )

    change_batch_id: Mapped[str] = mapped_column(String(32))
    action: Mapped[str] = mapped_column(String(16))
    record_snapshot: Mapped[str | None] = mapped_column(Text)
