"""hosted_zones table — DNS zone container (docs/DATABASE.md §4)."""

from __future__ import annotations

from typing import Final

from sqlalchemy import (
    CheckConstraint,
    ForeignKeyConstraint,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin

ZONE_TYPES: Final = ("public", "private")


class HostedZone(TimestampMixin, Base):
    """The zone id is `Z` + 13 uppercase alphanumerics (docs/DATABASE.md §1),
    generated by the service inside the creating transaction, so the model
    declares no Python default for it."""

    __tablename__ = "hosted_zones"
    __table_args__ = (
        CheckConstraint("id GLOB 'Z[A-Z0-9]*'", name="ck_hosted_zones_id_format"),
        CheckConstraint(
            "comment IS NULL OR length(comment) <= 256", name="ck_hosted_zones_comment_length"
        ),
        CheckConstraint("type IN ('public','private')", name="ck_hosted_zones_type_values"),
        CheckConstraint(
            "record_set_count >= 0", name="ck_hosted_zones_record_set_count_non_negative"
        ),
        UniqueConstraint("caller_reference", name="uq_hosted_zones_caller_reference"),
        UniqueConstraint("owner_user_id", "name", "type", name="uq_hosted_zones_owner_name_type"),
        ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            ondelete="CASCADE",
            name="fk_hosted_zones_owner_user_id_users",
        ),
        Index("ix_zones_owner_name", "owner_user_id", "name"),
    )

    id: Mapped[str] = mapped_column(String(32), primary_key=True)
    name: Mapped[str] = mapped_column(Text)
    comment: Mapped[str | None] = mapped_column(Text)
    type: Mapped[str] = mapped_column(String(16))
    vpc_id: Mapped[str | None] = mapped_column(String(32))
    vpc_region: Mapped[str | None] = mapped_column(String(32))
    caller_reference: Mapped[str] = mapped_column(String(64))
    record_set_count: Mapped[int] = mapped_column(Integer, server_default=text("0"), default=0)
    owner_user_id: Mapped[str] = mapped_column(String(32))
